### ISSUE TITLE
Android not building

### ISSUE THREAD

**Issue by Stas-Buzunko** [jesster2k10/react-native-range-slider#12]
Task :app:compileReleaseJavaWithJavac FAILED
/Users/bon/work/ff/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:15: error: cannot find symbol
import com.example.crystalrangeseekbar.ReactNativeRangeSliderPackage;
                                      ^
  symbol:   class ReactNativeRangeSliderPackage
  location: package com.example.crystalrangeseekbar
/Users/bon/work/ff/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:109: error: cannot find symbol
      new ReactNativeRangeSliderPackage(),
          ^
  symbol:   class ReactNativeRangeSliderPackage
  location: class PackageList

**Comment by Stas-Buzunko** [comment]
react-native: "0.62.1"
@jesster2k10/react-native-range-slider: "^0.3.1"

**Comment by devWaleed** [comment]
Auto linking is broken, follow manual linking steps
