### ISSUE TITLE
Could not find com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7.3.

### ISSUE THREAD

**Issue by jadrdev** [jesster2k10/react-native-range-slider#46]
Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.7.3/gradle-bintray-plugin-1.7.3.pom
       - https://repo.maven.apache.org/maven2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.7.3/gradle-bintray-plugin-1.7.3.pom

**Comment by nidhintrell** [comment]
@jadrdev what was the solution except for adding jcentre?

**Comment by jadrdev** [comment]
I didn't find any solution, in the end I changed this component for another.

**Comment by nidhintrell** [comment]
@jadrdev which one did u end up using? wanted something similar
